import './globals.css';
import type { Metadata } from 'next';
import { Lato } from 'next/font/google';

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${lato.className} bg-night text-white h-[90vh] md:h-[92.5vh]`}
      >
        <div className='border-2 border-white m-6 h-full p-4 rounded-sm overflow-hidden'>
          {children}
        </div>
      </body>
    </html>
  );
}
